name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test and Code Coverage
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[github_actions]
      - name: Unit test and code coverage on Python ${{ matrix.python-version }}
        run: tox
