name: Tags
on:
  push:
    tags:
      - 'v*'
jobs:
  upload:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.9
      - name: Build distributions
        # The following command(s) must produce ready-to-upload artifacts in the dist/ folder
        run: python setup.py dists
      - name: Upload distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
